In [25]:
import os
import re
import pandas as pd
filename='/Users/chenglinlin/ownCloud/BETA_AI_Gaze_Estimation_in_Human-Robot_Interaction (Projectfolder)/analized_data/analysis_dataset_neweth.csv'
df=pd.read_csv(filename)
df=df[(df['corrResp']==True)&(df['error_eth']<30)&(df['error_l2cs']<30)] 
df=df[df['person_ID'].isin(['2','4','12','13','14','15','18','19','20','21'])]
df

,Unnamed: 0,Unnamed: 0.1,dotNr,arrowOri,Resp,corrResp,fName,sampTime,Dot_xy,person_ID,...,3D_gaze,yp_gaze,virtual_l2cs,virtual_eth,yp_l2cs,yp_eth,3D_l2cs,3D_eth,error_l2cs,error_eth
0,0,0,7,right,right,True,2022_12_12_16_31_3_41513146_00001.jpg,424.461687,"[0.0,0.0]",20,...,"-0.1238554470030273,0.2927010812060677,-0.9481...","-0.1298932250135628,0.2970504172554897","16.842806230295217,-51.22537584235332","10.490430976656384,-46.342750539615295","-0.0354080582731485,0.0251005595901058","-0.06788486,0.047472775","-0.035389508745978,0.0250979239550237,-0.99905...","-0.06775631068048,0.0474549457256149,-0.996572...",16.466574,14.719538
1,1,1,7,right,right,True,2022_12_12_16_31_3_41513146_00002.jpg,425.909111,"[0.0,0.0]",20,...,"-0.1238554470030273,0.2927010812060677,-0.9481...","-0.1298932250135628,0.2970504172554897","20.60736372849538,-43.82119046411708","15.337876023385384,-48.190472833792576","-0.0169219918824724,0.0647491692669875","-0.043118037,0.040005535","-0.0168857260207708,0.0647039357544503,-0.9977...","-0.0430701889641975,0.0399948647586119,-0.9982...",14.747586,15.517128
2,2,2,7,right,right,True,2022_12_12_16_31_3_41513146_00003.jpg,426.239342,"[0.0,0.0]",20,...,"-0.1238554470030273,0.2927010812060677,-0.9481...","-0.1298932250135628,0.2970504172554897","12.042204249918122,-46.392991143153694","15.014045684434038,-50.43054034597771","-0.0599485550860106,0.0478855006123877","-0.04460706,0.0283339229999999","-0.0598439766919012,0.0478672022993367,-0.9970...","-0.0445743699709061,0.0283301320204229,-0.9986...",14.808984,16.129062
3,3,3,7,right,right,True,2022_12_12_16_31_3_41513146_00004.jpg,426.537674,"[0.0,0.0]",20,...,"-0.1238554470030273,0.2927010812060677,-0.9481...","-0.1298932250135628,0.2970504172554897","11.853943593290182,-45.61104124720395","8.95654180303952,-51.075553526989545","-0.0609770678989992,0.0518797096152886","-0.07524955,0.022194633","-0.0608572966221589,0.0518564403369868,-0.9967...","-0.0751600376237983,0.0221928108590965,-0.9969...",14.572706,16.046542
4,4,4,7,right,right,True,2022_12_12_16_31_3_41513146_00005.jpg,426.811700,"[0.0,0.0]",20,...,"-0.1238554470030273,0.2927010812060677,-0.9481...","-0.1298932250135628,0.2970504172554897","15.158354838821497,-82.35036588879039","21.0756067064425,-61.58594371448523","-0.0419842019528811,-0.1277337279956885","-0.014234843,-0.024825452","-0.0416299297497048,-0.1273866626833721,-0.990...","-0.014229976153416,-0.0248229020782096,-0.9995...",24.842595,19.565845
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
41782,41782,41782,4,left,left,True,2022_12_12_13_45_47_34199532_01346.jpg,1352.079732,"[921.6,504.0]",18,...,"0.2016371072447534,0.2147862614877875,-0.95561...","0.2079510807656757,0.2164729784282918","111.9836215838071,-27.714029990224944","50.06836243115431,-8.01247335078558","0.3185060768902066,0.0410819229755623","0.1564952,0.096779056","0.3128839086884055,0.0410703681234066,-0.94890...","0.1551278767870759,0.0966280516326878,-0.98315...",11.846554,7.449903
41783,41783,41783,4,left,left,True,2022_12_12_13_45_47_34199532_01347.jpg,1352.379178,"[921.6,504.0]",18,...,"0.2016371072447534,0.2147862614877875,-0.95561...","0.2079510807656757,0.2164729784282918","58.95261039828437,6.302573124290561","18.522285099275656,-31.206370521676195","0.1810816383199378,0.1345114729699401","0.07145786,0.036245257","0.178466839266621,0.1341062128816164,-0.974764...","0.0713501695046382,0.0362373215095553,-0.99679...",4.934500,12.909238
41784,41784,41784,4,left,left,True,2022_12_12_13_45_47_34199532_01348.jpg,1352.673695,"[921.6,504.0]",18,...,"0.2016371072447534,0.2147862614877875,-0.95561...","0.2079510807656757,0.2164729784282918","74.31819588838601,-8.333655955098024","52.12633381284305,-37.71516645540667","0.2212937728834802,0.0945997429773586","0.16056027,0.017697128","0.2185106326479672,0.0944587088260668,-0.97125...","0.1598462611507892,0.0176962042587768,-0.98698...",7.023493,11.702861
41785,41785,41785,4,left,left,True,2022_12_12_13_45_47_34199532_01349.jpg,1352.965262,"[921.6,504.0]",18,...,"0.2016371072447534,0.2147862614877875,-0.95561...","0.2079510807656757,0.2164729784282918","58.72561950298627,-20.101337430460926","11.417606565272546,-54.74979597383108","0.1790294063839227,0.0641459632800845","0.052259095,-0.025417143","0.1777083403054866,0.0641019820477972,-0.98199...","0.0522184396254252,-0.0254144063773432,-0.9983...",8.880281,16.447914
41786,41786,41786,4,left,left,True,2022_12_12_13_45_47_34199532_01350.jpg,1353.248138,"[921.6,504.0]",18,...,"0.2016371072447534,0.2147862614877875,-0.95561...","0.2079510807656757,0.2164729784282918","55.007895762908745,1.7554086123642207","74.44930355558529,-71.51491279190995","0.1702377789933531,0.1226012839428878","0.21749133,-0.07137095","0.1681450321917423,0.1222943765123888,-0.97814...","0.2152313942335086,-0.0713103737240138,-0.9739...",5.784488,16.501188

In [26]:
df['3D_gaze']=df['3D_gaze'].str.split(',')
df['yp_gaze']=df['yp_gaze'].str.split(',')
df['yp_l2cs']=df['yp_l2cs'].str.split(',')
df['yp_eth']=df['yp_eth'].str.split(',')
def get_yaw_pitch(row):
    row['x']=round(float(row['3D_gaze'][0]),3)
    row['y']=round(float(row['3D_gaze'][1]),3)
    row['z']=round(float(row['3D_gaze'][2]),3)
    row['yaw']=round(float(row['yp_gaze'][0]),3)/3.14*180
    row['pitch']=round(float(row['yp_gaze'][1]),3)/3.14*180
    row['yaw_l2cs']=round(float(row['yp_l2cs'][0]),3)/3.14*180
    row['pitch_l2cs']=round(float(row['yp_l2cs'][1]),3)/3.14*180
    row['yaw_eth']=round(float(row['yp_eth'][0]),3)/3.14*180
    row['pitch_eth']=round(float(row['yp_eth'][1]),3)/3.14*180
    return row    

df=df.apply(get_yaw_pitch,axis='columns')

In [27]:
df['yaw_error_l2cs']=df['yaw']-df['yaw_l2cs']
df['pitch_error_l2cs']=df['pitch']-df['pitch_l2cs']
df['yaw_error_eth']=df['yaw']-df['yaw_eth']
df['pitch_error_eth']=df['pitch']-df['pitch_eth']
p=[2,4,12,13,14,15,18,19,20,21]
i=0
ay=df[(df['4k']==False)&(~df['person_ID'].isin([p[i],p[i+1]]))]['yaw_error_eth'].mean()
ap=df[(df['4k']==False)&(~df['person_ID'].isin([p[i],p[i+1]]))]['pitch_error_eth'].mean()
(ay,ap),(ay,ap)
df

,Unnamed: 0,Unnamed: 0.1,dotNr,arrowOri,Resp,corrResp,fName,sampTime,Dot_xy,person_ID,...,yaw,pitch,yaw_l2cs,pitch_l2cs,yaw_eth,pitch_eth,yaw_error_l2cs,pitch_error_l2cs,yaw_error_eth,pitch_error_eth
0,0,0,7,right,right,True,2022_12_12_16_31_3_41513146_00001.jpg,424.461687,"[0.0,0.0]",20,...,-7.452229,17.025478,-2.006369,1.433121,-3.898089,2.694268,-5.445860,15.592357,-3.554140,14.331210
1,1,1,7,right,right,True,2022_12_12_16_31_3_41513146_00002.jpg,425.909111,"[0.0,0.0]",20,...,-7.452229,17.025478,-0.974522,3.726115,-2.464968,2.292994,-6.477707,13.299363,-4.987261,14.732484
2,2,2,7,right,right,True,2022_12_12_16_31_3_41513146_00003.jpg,426.239342,"[0.0,0.0]",20,...,-7.452229,17.025478,-3.439490,2.751592,-2.579618,1.605096,-4.012739,14.273885,-4.872611,15.420382
3,3,3,7,right,right,True,2022_12_12_16_31_3_41513146_00004.jpg,426.537674,"[0.0,0.0]",20,...,-7.452229,17.025478,-3.496815,2.980892,-4.299363,1.261146,-3.955414,14.044586,-3.152866,15.764331
4,4,4,7,right,right,True,2022_12_12_16_31_3_41513146_00005.jpg,426.811700,"[0.0,0.0]",20,...,-7.452229,17.025478,-2.407643,-7.337580,-0.802548,-1.433121,-5.044586,24.363057,-6.649682,18.458599
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
41782,41782,41782,4,left,left,True,2022_12_12_13_45_47_34199532_01346.jpg,1352.079732,"[921.6,504.0]",18,...,11.923567,12.382166,18.286624,2.350318,8.942675,5.560510,-6.363057,10.031847,2.980892,6.821656
41783,41783,41783,4,left,left,True,2022_12_12_13_45_47_34199532_01347.jpg,1352.379178,"[921.6,504.0]",18,...,11.923567,12.382166,10.375796,7.738854,4.070064,2.063694,1.547771,4.643312,7.853503,10.318471
41784,41784,41784,4,left,left,True,2022_12_12_13_45_47_34199532_01348.jpg,1352.673695,"[921.6,504.0]",18,...,11.923567,12.382166,12.668790,5.445860,9.229299,1.031847,-0.745223,6.936306,2.694268,11.350318
41785,41785,41785,4,left,left,True,2022_12_12_13_45_47_34199532_01349.jpg,1352.965262,"[921.6,504.0]",18,...,11.923567,12.382166,10.261146,3.668790,2.980892,-1.433121,1.662420,8.713376,8.942675,13.815287
41786,41786,41786,4,left,left,True,2022_12_12_13_45_47_34199532_01350.jpg,1353.248138,"[921.6,504.0]",18,...,11.923567,12.382166,9.745223,7.050955,12.439490,-4.070064,2.178344,5.331210,-0.515924,16.452229

In [28]:
import numpy as np
def sphere2cartesian(row):
    x0=row['yaw']
    x1=row['pitch']
    row['x']=np.cos(x1) * np.sin(x0)
    row['y']=np.sin(x1)  
    row['z']=-np.cos(x0) * np.cos(x1)
    return row

def error3d(a,b):
    a=a.to_numpy()
    b=b.to_numpy()
    e=[]
    for i in range(len(a)):
        error = np.arccos(np.dot(a[i], b[i]))
        e.append(error)
    dfe = pd.DataFrame(e)*180/3.1415926
    return dfe

def comp(idealgaze,pregaze,offset_y,offset_p):  
    pregaze['pitch']=pregaze['pitch']/180*3.14+offset_p/180*3.14#just test 0.122(7 degree) 0,105(6 degree)
    pregaze['yaw']=pregaze['yaw']/180*3.14+offset_y/180*3.14#just test 0.122(7 degree) 0,105(6 degree)

    pregaze=pregaze.apply(sphere2cartesian,axis='columns')  

    error=error3d(pregaze[['x','y','z']],idealgaze[['x','y','z']])
    return error.mean()

In [29]:
pregaze=df[(df['4k']==False)&(df['person_ID'].isin([p[i],p[i+1]]))][['yaw_eth','pitch_eth']].rename({'yaw_eth': 'yaw','pitch_eth': 'pitch'}, axis='columns')
#pregaze=pregaze.rename({'yaw_eth': 'yaw','pitch_eth': 'pitch'}, axis='columns')
idealgaze=df[(df['4k']==False)&(df['person_ID'].isin([p[i],p[i+1]]))][['x','y','z']]
en=comp(idealgaze,pregaze,ay,ap)[0]
e=df[(df['4k']==False)&(df['person_ID'].isin([p[i],p[i+1]]))]['error_eth'].mean()

/opt/anaconda3/envs/psychopy/lib/python3.6/site-packages/ipykernel_launcher.py:15: RuntimeWarning: invalid value encountered in arccos
  from ipykernel import kernelapp as app

In [30]:
df[(df['4k']==False)&(df['person_ID'].isin([p[i],p[i+1]]))]['error_eth'].mean()
en

9.259112848240594

In [31]:
p=[12,4,2,13,14,15,18,19,20,21]

#a=df[(df['4k']==False)&(df['person_ID'].isin([p[0],p[i+1]]))]['yaw_error_eth'].mean()
t= pd.DataFrame(index=range(5), columns=range(17))

for i in [0,2,4,6,8]:
    ay=df[(df['4k']==False)&(~df['person_ID'].isin([p[i],p[i+1]]))]['yaw_error_eth'].mean()
    ap=df[(df['4k']==False)&(~df['person_ID'].isin([p[i],p[i+1]]))]['pitch_error_eth'].mean()
    by=df[(df['4k']==False)&(~df['person_ID'].isin([p[i],p[i+1]]))]['yaw_error_l2cs'].mean()
    bp=df[(df['4k']==False)&(~df['person_ID'].isin([p[i],p[i+1]]))]['pitch_error_l2cs'].mean()
    cy=df[(df['4k']==True)&(~df['person_ID'].isin([p[i],p[i+1]]))]['yaw_error_eth'].mean()
    cp=df[(df['4k']==True)&(~df['person_ID'].isin([p[i],p[i+1]]))]['pitch_error_eth'].mean()
    dy=df[(df['4k']==True)&(~df['person_ID'].isin([p[i],p[i+1]]))]['yaw_error_l2cs'].mean()
    dp=df[(df['4k']==True)&(~df['person_ID'].isin([p[i],p[i+1]]))]['pitch_error_l2cs'].mean()
    
    idealgaze1=df[(df['4k']==False)&(df['person_ID'].isin([p[i],p[i+1]]))][['x','y','z']]
    idealgaze2=df[(df['4k']==True)&(df['person_ID'].isin([p[i],p[i+1]]))][['x','y','z']]
    
    apregaze=df[(df['4k']==False)&(df['person_ID'].isin([p[i],p[i+1]]))][['yaw_eth','pitch_eth']].rename({'yaw_eth': 'yaw','pitch_eth': 'pitch'}, axis='columns')
    bpregaze=df[(df['4k']==False)&(df['person_ID'].isin([p[i],p[i+1]]))][['yaw_l2cs','pitch_l2cs']].rename({'yaw_l2cs': 'yaw','pitch_l2cs': 'pitch'}, axis='columns')
    cpregaze=df[(df['4k']==True)&(df['person_ID'].isin([p[i],p[i+1]]))][['yaw_eth','pitch_eth']].rename({'yaw_eth': 'yaw','pitch_eth': 'pitch'}, axis='columns')
    dpregaze=df[(df['4k']==True)&(df['person_ID'].isin([p[i],p[i+1]]))][['yaw_l2cs','pitch_l2cs']].rename({'yaw_l2cs': 'yaw','pitch_l2cs': 'pitch'}, axis='columns')
    
    ay=round(ay,2)
    by=round(by,2)
    cy=round(cy,2)
    dy=round(dy,2)
    ap=round(ap,2)
    bp=round(bp,2)
    cp=round(cp,2)
    dp=round(dp,2)
   
    a_en=comp(idealgaze1,apregaze,ay,ap)[0]
    b_en=comp(idealgaze1,bpregaze,by,bp)[0]
    c_en=comp(idealgaze2,cpregaze,cy,cp)[0]
    d_en=comp(idealgaze2,dpregaze,dy,dp)[0]
    
    a_e=df[(df['4k']==False)&(df['person_ID'].isin([p[i],p[i+1]]))]['error_eth'].mean()
    b_e=df[(df['4k']==False)&(df['person_ID'].isin([p[i],p[i+1]]))]['error_l2cs'].mean()
    c_e=df[(df['4k']==True)&(df['person_ID'].isin([p[i],p[i+1]]))]['error_eth'].mean()
    d_e=df[(df['4k']==True)&(df['person_ID'].isin([p[i],p[i+1]]))]['error_l2cs'].mean()
    
    a_en=round(a_en,2)
    b_en=round(b_en,2)
    c_en=round(c_en,2)
    d_en=round(d_en,2)
    a_e=round(a_e,2)
    b_e=round(b_e,2)
    c_e=round(c_e,2)
    d_e=round(d_e,2)
   
    t[1][i/2]=ay
    t[2][i/2]=ap
    t[3][i/2]=by
    t[4][i/2]=bp
    t[5][i/2]=cy
    t[6][i/2]=cp
    t[7][i/2]=dy
    t[8][i/2]=dp
    
    t[9][i/2]=a_en
    t[10][i/2]=a_e
    t[11][i/2]=b_en
    t[12][i/2]=b_e
    t[13][i/2]=c_en
    t[14][i/2]=c_e
    t[15][i/2]=d_en
    t[16][i/2]=d_e
    
    print((ay,ap),(by,bp),(cy,cp),(dy,dp))
    print((a_en,a_e),(b_en,b_e),(c_en,c_e),(d_en,d_e))

/opt/anaconda3/envs/psychopy/lib/python3.6/site-packages/ipykernel_launcher.py:15: RuntimeWarning: invalid value encountered in arccos
  from ipykernel import kernelapp as app

(2.09, 7.76) (2.35, 7.72) (-0.05, 6.03) (0.95, 6.61)
(8.9, 9.53) (8.27, 8.97) (6.58, 8.59) (8.84, 9.77)

/opt/anaconda3/envs/psychopy/lib/python3.6/site-packages/ipykernel_launcher.py:15: RuntimeWarning: invalid value encountered in arccos
  from ipykernel import kernelapp as app

(2.73, 6.44) (1.25, 7.35) (0.65, 6.26) (0.67, 6.44)
(11.39, 13.89) (9.12, 11.24) (10.2, 10.76) (7.45, 8.91)

/opt/anaconda3/envs/psychopy/lib/python3.6/site-packages/ipykernel_launcher.py:15: RuntimeWarning: invalid value encountered in arccos
  from ipykernel import kernelapp as app

(2.1, 7.6) (1.93, 7.62) (0.46, 5.88) (0.85, 6.17)
(10.24, 11.22) (7.87, 9.65) (9.26, 10.99) (6.39, 9.14)

/opt/anaconda3/envs/psychopy/lib/python3.6/site-packages/ipykernel_launcher.py:15: RuntimeWarning: invalid value encountered in arccos
  from ipykernel import kernelapp as app

(2.74, 6.13) (2.29, 6.5) (1.14, 5.8) (1.05, 6.42)
(9.99, 13.44) (7.51, 11.98) (6.35, 8.96) (6.55, 8.58)

/opt/anaconda3/envs/psychopy/lib/python3.6/site-packages/ipykernel_launcher.py:15: RuntimeWarning: invalid value encountered in arccos
  from ipykernel import kernelapp as app

(3.21, 7.07) (2.8, 7.18) (1.98, 6.22) (1.22, 6.75)
(11.38, 12.32) (9.6, 11.82) (9.16, 9.48) (8.47, 9.24)

In [50]:
tt=t
t[2.5]=(t[10]-t[9])/t[10]*100
t[4.5]=(t[12]-t[11])/t[12]*100
t[6.5]=(t[14]-t[13])/t[14]*100
t[8.5]=(t[16]-t[15])/t[16]*100

In [52]:
t[[1,2,2.5,3,4,4.5,5,6,6.5,7,8,8.5]].mean()

1.0     2.574000
2.0     7.000000
2.5    13.328636
3.0     2.124000
4.0     7.274000
4.5    20.240902
5.0     0.836000
6.0     6.038000
6.5    15.370067
7.0     0.948000
8.0     6.478000
8.5    17.597111
dtype: float64

In [47]:
t[[4.5]]

       4.5
0  7.80379
1  18.8612
2  18.4456
3  37.3122
4  18.7817

In [40]:
t[[1,2,2.5,3,4,4.5,5,6,6.5,7,8,8.5]].mean()

1.0    2.574000
2.0    7.000000
2.5    0.133286
3.0    2.124000
4.0    7.274000
4.5   -0.125012
5.0    0.836000
6.0    6.038000
6.5   -0.110161
7.0    0.948000
8.0    6.478000
8.5   -0.071905
dtype: float64

In [83]:
round((ay,by),2)

TypeError: type tuple doesn't define __round__ method

In [67]:
cp

5.39

In [70]:
c_en=comp(idealgaze,cpregaze,cy,cp)[0]

/opt/anaconda3/envs/psychopy/lib/python3.6/site-packages/ipykernel_launcher.py:15: RuntimeWarning: invalid value encountered in arccos
  from ipykernel import kernelapp as app

IndexError: index 2078 is out of bounds for axis 0 with size 2078

In [76]:
bpregaze=df[(df['4k']==False)&(df['person_ID'].isin([p[i],p[i+1]]))][['yaw_l2cs','pitch_l2cs']].rename({'yaw_l2cs': 'yaw','pitch_l2cs': 'pitch'}, axis='columns')
cpregaze=df[(df['4k']==True)&(df['person_ID'].isin([p[i],p[i+1]]))][['yaw_eth','pitch_eth']].rename({'yaw_eth': 'yaw','pitch_eth': 'pitch'}, axis='columns')

In [77]:
cpregaze

             yaw     pitch
35037 -25.108280 -0.515924
35038 -27.343949 -2.178344
35039 -31.070064  2.579618
35040 -32.331210 -0.573248
35041 -33.019108  0.458599
...          ...       ...
37732   7.566879  6.878981
37733  13.643312  6.592357
37734  10.375796  3.210191
37735  11.808917  9.057325
37736   8.885350  7.337580

[2646 rows x 2 columns]

In [78]:
bpregaze

             yaw      pitch
1350  -14.904459   6.993631
1351  -18.687898   7.280255
1352  -17.426752   5.675159
1353  -17.770701   9.974522
1354  -17.312102  10.547771
...          ...        ...
10740   6.649682   3.554140
10741  10.089172   4.585987
10742  16.337580   1.146497
10743  13.127389  -0.057325
10744  10.146497   4.471338

[2641 rows x 2 columns]

In [79]:
idealgaze

           x      y      z
1350  -0.311  0.297 -0.903
1351  -0.311  0.297 -0.903
1352  -0.311  0.297 -0.903
1353  -0.311  0.297 -0.903
1354  -0.311  0.297 -0.903
...      ...    ...    ...
10740  0.202  0.220 -0.954
10741  0.202  0.220 -0.954
10742  0.202  0.220 -0.954
10743  0.202  0.220 -0.954
10744  0.202  0.220 -0.954

[2641 rows x 3 columns]